# config/app.yaml
_target_: processor.app.RealtimeApp
_recursive_: false

time_counter:
  _target_: processor.timer.TimeCounter
  save_dir: results

reader:
  _target_: processor.reader.FFmpegRTSPReader
  rtsp_url: rtsp://member:AIST-rwdc@192.168.0.10:554/ONVIF/MediaInput?profile=def_profile1
  size: [1920, 1080]
  transport: udp
  output_fps: 30
  frame_queue_maxsize: 100
  flush_on_queue_full: true

displayer:
  _target_: processor.displayer.Displayer
  window_name: realtime
  maxsize: 100
  freq_to_report_fps: 100
  flush_on_queue_full: true
  report_single: false
  report_avg: true

# MOT worker
worker:
  _target_: processor.worker.MotWorker
  detectors:
    - _target_: processor.components.Detector
      detector: 
        _target_: pipeline.detector.p2pnet.P2PNetDetector
        cfg_path: modules/detector/p2pnet/conf/p2p.yaml
        weight_path: weights/p2pnet/cutout.pth
        device: cuda:0
        dtype: float16
        threshold: 0.1
        img_size: [1080, 1920]
      devide_size: null
    - _target_: processor.components.Detector
      detector: 
        _target_: pipeline.detector.yolo26.YOLODetector
        model_size: x
        weight_dir: weights/yolo26
        img_long_side: 1920
        device: cuda:0
        conf_threshold: 0.01
        iou_threshold: 0.7
      devide_size: null
  trackers:
    - _target_: processor.components.Tracker
      tracker: 
        _target_: pipeline.tracker.point_bytetrack.PointByteTrackTracker
        track_thresh: 0.6
        track_buffer: 30
        match_thresh: 10.0
        distance_metric: euclidean
        frame_rate: 30
    - _target_: processor.components.Tracker
      tracker:
        _target_: pipeline.tracker.bytetrack.ByteTrackTracker
        track_thresh: 0.5
        track_buffer: 30
        match_thresh: 0.8
        mot20: False
        frame_rate: 30
    
# worker:
#   _target_: processor.worker.MotWorker
#   detectors:
#     - _target_: processor.components.Detector
#       detector: pipeline/config/detector/p2pnet/p2pnet.yaml
#       devide_size: null
#     - _target_: processor.components.Detector
#       detector: pipeline/config/detector/yolo26/yolo26.yaml
#       devide_size: null
#   trackers:
#     - _target_: processor.components.Tracker
#       tracker: pipeline/config/tracker/point_bytetrack/point_bytetrack.yaml
#     - _target_: processor.components.Tracker
#       tracker: pipeline/config/tracker/bytetrack/bytetrack.yaml

# Pose worker
# worker:
#   _target_: processor.worker.PoseWorker

max_wall_seconds: null