_target_: pipeline.detector.yolo26.YOLODetector

model_size: x
weight_dir: weights/yolo26
img_long_side: 1920
device: cuda:0
conf_threshold: 0.01
iou_threshold: 0.7
classes: [1, 2, 3, 5, 6, 7] # bicycle, car, motorcycle, bus, train, truck